### ISSUE TITLE
Can't use command /money

### ISSUE THREAD

**Issue by tincopper2** [Flibio/EconomyLite#11]
These mods running on server:
spongeforge-1.10.2-2011-5.0.0-BETA-1570
EconomyLite 2.2.3
Polis 1.10.2-2.6.8
industrialcraft-2-2.6.13-ex110

Forge build 2011, client running same and only mod on client is industrialcraft-2-2.6.13-ex110.

[Here's the error](http://pastebin.com/Apam7SAA)

**Comment by Flibio** [comment]
@tincopper2: EconomyLite isn't updated for API 5 yet. I'll create a development build for you quick.

**Comment by Flibio** [comment]
@tincopper2: I've created a development build, here is the link: http://downloads.flibio.net/EconomyLite-5.0.0-v2.2.3.jar.

**Comment by tincopper2** [comment]
You didn't have to do all that for just me, but thanks.
