### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GershonR** [Flibio/EconomyLite#12]
http://pastebin.com/RFZcJiJs

**Comment by Flibio** [comment]
What version of EconomyLite are you using?

**Comment by Flibio** [comment]
@GershonR: When does this crash occur?

**Comment by GershonR** [comment]
On startup

**Comment by Flibio** [comment]
@GershonR: Can you send me the contents of your config/EconomyLite folder? Feel free to PM me on the forums if you don't want the folder to be public.

**Comment by Flibio** [comment]
@GershonR: Can you please paste the entire `fml-server-latest` file? I can't seen to replicate the error.

**Comment by Flibio** [comment]
@GershonR: Is this issue still occurring?

**Comment by GershonR** [comment]
Don't think so
