### ISSUE TITLE
Error on startup of Sponge API 5 1.10.2

### ISSUE THREAD

**Issue by LucidTheStick** [Flibio/EconomyLite#13]
Error on startup.  Fails to register as an Economy plugin for JobsLite.

http://pastebin.com/FqZXcUdU

**Comment by Flibio** [comment]
Can you post your config file?

**Comment by LucidTheStick** [comment]
You beat me to this.  Was about to close it.  Can't use $ like symbol=$
coin {
    plural=Coins
    singular=Coin
    symbol=$
}

**Comment by Flibio** [comment]
Yes, also, EconomyLite has not been updated for Sponge API 5. Here is a development build: http://downloads.flibio.net/EconomyLite-5.0.0-v2.2.3.jar.
