### ISSUE TITLE
A problem.

### ISSUE THREAD

**Issue by 5igm** [Flibio/EconomyLite#14]
I both installed "EconomyLite-5.0.0-v2.2.4.jar" and "Nations-0.8.jar" as server's plugins. However when I tried to run a command in Nation plugin, there were some problems. After I reported this problem to the author of Nation plugin, he told me this problem is from the economic plugin.

This is the orginal page where I contacted with Arckenver.
https://github.com/Arckenver/Nations/issues/5

> Sure. In fact, any sponge plugin that has to make money transactions uses the Sponge Economy API. Economy plugins just implements that API, which means any plugin that uses economy (like Nations) is compatible with any economy plugin (like EconomyLite).
> 
> Our problem is explained here Value too long for column "ID VARCHAR(36)": "'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' (43)" which means that Nations is trying to create an account named nation-0821d04a-e64c-437c-8a6a-1a8635e9175e (which is the account of a newly created nation) but EconomyLite doesn't accept names with more than 36 characters.
> 
> But that is really strange given that in version 2.0.5 of EconomyLite, Flibio said he solved that problem (see here) so in v2.2.4 it should still be solved. Are you sure you of your EconomyLite version ? If so then that's an issue concerning that plugin, and I recommend you report it to Flibio.

**Comment by 5igm** [comment]
This is the error log.
`[18:20:33] [HikariPool-2 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-2 - Pool stats (total=17, active=2, idle=15, waiting=0) [18:20:38] [HikariPool-3 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-3 - Pool stats (total=17, active=2, idle=15, waiting=0) [18:20:56] [HikariPool-1 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-1 - Pool stats (total=17, active=0, idle=17, waiting=0) [18:21:03] [HikariPool-2 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-2 - Pool stats (total=17, active=2, idle=15, waiting=0) [18:21:08] [HikariPool-3 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-3 - Pool stats (total=17, active=2, idle=15, waiting=0) [18:21:08] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world [18:21:16] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7fee72a1-cda1-304c-9520-4adafc83118d' exists with 'economylite:Coins' - Cause[{Name=New account check, Object={org.spongepowered.mod.plugin.SpongeModPluginContainer@53755603}}] = true [18:21:16] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7fee72a1-cda1-304c-9520-4adafc83118d' - Cause[{Name=Get Balance, Object={org.spongepowered.mod.plugin.SpongeModPluginContainer@53755603}}] = 994999.00 [18:21:16] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7fee72a1-cda1-304c-9520-4adafc83118d' - Cause[{Name=Source, Object={com.arckenver.nations.NationsPlugin@11f8eec7}}] = 994999.00 [18:21:16] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7fee72a1-cda1-304c-9520-4adafc83118d' exists with 'economylite:Coins' - Cause[{Name=Source, Object={com.arckenver.nations.NationsPlugin@11f8eec7}}] = true [18:21:16] [Server thread/DEBUG] [economylite/]: playercommon: +Account Exists+ Setting balance of '7fee72a1-cda1-304c-9520-4adafc83118d' to '992499.00' with 'economylite:Coins' - Cause[{Name=Source, Object={com.arckenver.nations.NationsPlugin@11f8eec7}}] = true [18:21:16] [Server thread/DEBUG] [economylite/]: virtcommon: Checking if 'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' exists with 'economylite:Coins' - Cause[{Name=New account check, Object={org.spongepowered.mod.plugin.SpongeModPluginContainer@53755603}}] = false [18:21:16] [Server thread/DEBUG] [economylite/]: virtcommon: Checking if 'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' exists with 'economylite:Coins' - Cause[{Name=Creating account, Object={org.spongepowered.mod.plugin.SpongeModPluginContainer@53755603}}] = false [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: org.h2.jdbc.JdbcSQLException: Value too long for column "ID VARCHAR(36)": "'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' (43)"; SQL statement: INSERT INTO economylitevirts (id,balance,currency) VALUES (?, ?, ?) [22001-192] [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.message.DbException.get(DbException.java:179) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.table.Column.validateConvertUpdateSequence(Column.java:335) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.command.dml.Insert.insertRows(Insert.java:151) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.command.dml.Insert.update(Insert.java:114) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.command.CommandContainer.update(CommandContainer.java:98) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.command.Command.executeUpdate(Command.java:258) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at io.github.flibio.economylite.utils.sql.SqlManager.executeUpdate(SqlManager.java:118) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at io.github.flibio.economylite.impl.VirtualServiceCommon.setBalance(VirtualServiceCommon.java:77) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:81) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at com.arckenver.nations.cmdexecutor.nation.NationCreateExecutor.execute(NationCreateExecutor.java:111) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at java.util.concurrent.FutureTask.run(Unknown Source) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.util.Util.func_181617_a(SourceFile:45) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [18:21:16] [Server thread/INFO] [STDERR/]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: at java.lang.Thread.run(Unknown Source) [18:21:16] [Server thread/ERROR] [economylite/]: Value too long for column "ID VARCHAR(36)": "'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' (43)"; SQL statement: INSERT INTO economylitevirts (id,balance,currency`) VALUES (?, ?, ?) [22001-192]
[18:21:16] [Server thread/DEBUG] [economylite/]: virtcommon: +Account Does Not Exist+ Setting balance of 'nation-0821d04a-e64c-437c-8a6a-1a8635e9175e' to '0.0' with 'economylite:Coins' - Cause[{Name=Creating account, Object={org.spongepowered.mod.plugin.SpongeModPluginContainer@5375560}}] = false
[18:21:16] [Server thread/ERROR] [com.arckenver.nations/]: Could not create nation's account on the economy service !`

**Comment by Flibio** [comment]
Fixed in EconomyLite v2.2.5.
