### ISSUE TITLE
/Business does not work

### ISSUE THREAD

**Issue by crymates** [Flibio/EconomyLite#19]
/business is currently not an registered command on last build.
I use spongeforge-1.10.2-2123-6.0.0-BETA-1890 and ur development build EconomyLite-6.0.0-2.3.0.

Greetz,
yololetsplay

**Comment by Flibio** [comment]
`/business` is not a command in EconomyLite 2. It was a command in EconomyLite 1, but it was cut from the plugin in the 2.0 release.
