### ISSUE TITLE
Add /pay to virtual accounts

### ISSUE THREAD

**Issue by crymates** [Flibio/EconomyLite#20]
Hey there :]

Can u add the possibility to pay to virtual accounts?

**Comment by Flibio** [comment]
Virtual accounts are only meant to be created by other plugins. For example, the Nations plugin creates virtual accounts. Why do would you like to pay a virtual account?

**Comment by crymates** [comment]
First, thx for answering to all issues that quickly :]

I'd like to pay with an virtual account like....
You have an virtual account called "kingdom".
The kingdom can has it's own shops and job payments are also made by the kingdom.
I hope you know what I mean :]

**Comment by Flibio** [comment]
I'll look into adding it.

**Comment by crymates** [comment]
Btw. look at sponge forum :]

Thx btw.!
