### ISSUE TITLE
Permissions does not work on newest build

### ISSUE THREAD

**Issue by crymates** [Flibio/EconomyLite#21]
The permissions are not working currently :/

                        "econ.playerbalance": 1,
                        "econ.pay": 1,
                        "econ.business.register": 1,
                        "econ.business.delete": 1,
                        "econ.business.leave": 1,
                        "econ.business.invite": 1,
                        "econ.business.transfer": 1,

Using ur latest development build EconomyLite-6.0.0-2.3.0 and spongeforge-1.10.2-2123-6.0.0-BETA-1890.

**Comment by Flibio** [comment]
You appear to be looking at incorrect documentation. The permissions for the latest versions are found on the [docs](http://flibiostudio.github.io/EconomyLiteDocs/commands.html).
