### ISSUE TITLE
Feature request - when you get paid give feedback.

### ISSUE THREAD

**Issue by ProsperCraft** [Flibio/EconomyLite#22]
When you receive funds it would be nice if you got a chat notification.

**Comment by Flibio** [comment]
If the player is online when someone uses the `/pay` command they will receive a message.

**Comment by ProsperCraft** [comment]
Sorry, I should have been more specific, when they get creds with /econ add name

**Comment by Flibio** [comment]
I'm not sure about implementing this, because the `/econ` commands are meant to be administrative commands. I'll think about it and probably add it as a configuration option when I have time.

**Comment by Flibio** [comment]
1c6a27c559fee35140fa6d4fac4c95454fcb9a27
