### ISSUE TITLE
Config location seems hard coded.

### ISSUE THREAD

**Issue by ProsperCraft** [Flibio/EconomyLite#23]
Sponge just added the ability to specify config location, all plugins respect it, but for some reason economy lite has the /config folder hard coded, please correct.

**Comment by Flibio** [comment]
It is indeed hard coded as I wrote this plugin a long time ago when I did not know of Sponge's configuration services so I had to write my configuration system. Sometime, I'll update this.

**Comment by Flibio** [comment]
1c6a27c559fee35140fa6d4fac4c95454fcb9a27
