### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by GershonR** [Flibio/EconomyLite#24]
The plugin seems to throw internal errors when used:

http://pastebin.com/2af4DPMd

EconomyLite v2.6.0 (2 days ago 1)

Minecraft: 1.10.2
SpongeAPI: 6.0.0-SNAPSHOT-24eb858
SpongeForge: 1.10.2-2123-6.0.0-BETA-1902
Minecraft Forge: 12.18.2.2151

**Comment by Flibio** [comment]
Thanks for reporting this, I'll try to get a fix out shortly.

**Comment by Flibio** [comment]
dd6b71c4c7959378bd1bf69ad3b22bca1019bc1e
