### ISSUE TITLE
Dollar symbol issue

### ISSUE THREAD

**Issue by EnderZaMan** [Flibio/EconomyLite#25]
How do I specify the dollar sign ($) in currencies? I do it and then it just crashes. I didn't change any formatting either. This is in my currencies config:

dollar {
    plural=Dollars
    singular=Dollar
    symbol=$
}
current=dollar

Forge latest log:
http://pastebin.com/YVX8DU1k

**Comment by Flibio** [comment]
Put a set of quotations around the symbol, I believe that will fix it.

**Comment by EnderZaMan** [comment]
Thank you!
