### ISSUE TITLE
Invalid /baltop

### ISSUE THREAD

**Issue by aso824** [Flibio/EconomyLite#26]
I have PayDay installed and my ballance increases every X minutes. It works - I check /bal after getting some cash and I see that it increased.
But /baltop don't see change - still displays previous number (before I get money from PayDay).
What is weird - i'm OP on server, my friends also get money from PayDay but his account status is displayed correctly on /baltop list (it's increasing every X minutes)

**Comment by Flibio** [comment]
Can you please test `/baltop` using the `/econ` admin commands to change balances instead of PayDay?

**Comment by aso824** [comment]
`/econ set` and `/baltop`: when I change someone's else account, `baltop` see changes. When I change my balance, `baltop` still displays previous balance.

My tests in console: http://pastebin.com/0hGh7bJn

**Comment by Flibio** [comment]
Does the balance ever update or is permanently stuck at a certain amount? Which Sponge version and EconomyLite version are you using? I unfortunately can not reproduce the issue.

**Comment by aso824** [comment]
Ok, I found what was a problem - my nickname had two different UUIDs, in server cache and `data.mv.db` file. After removing row and entry in `usernamecache.json`, everything work correctly.

**Comment by Flibio** [comment]
Glad to hear you got it figured out!
