### ISSUE TITLE
Registering service order

### ISSUE THREAD

**Issue by vectrixdevelops** [Flibio/EconomyLite#29]
It seems that EconomyLite is not registering the economy service in the pre-load events, causing some plugins to not hook correctly with the service. Either that, or the other plugins could be at fault (I haven't looked into this as much as I probably should have).

**Comment by Flibio** [comment]
Can you provide some example plugins that fail?

I'll take a look at this this weekend.

**Comment by vectrixdevelops** [comment]
It would be great if you could register the economy service on GamePreInitializationEvent instead of GameInitializationEvent. (I looked at some other Economy plugins and they did this)

There are a fair few plugins that don't like it being loaded after too much.
