### ISSUE TITLE
Plugin loading error

### ISSUE THREAD

**Issue by AdnanMia** [Flibio/EconomyLite#32]
[main/TRACE] [Sponge]: Scanning mods/EconomyLite-5.0.0-2.7.0.jar for plugins
[main/ERROR] [Sponge]: Skipping plugin with duplicate plugin ID 'economylite' from mods/EconomyLite-5.0.0-2.7.0.jar

Using the latest plugin and sponge version 1.11.2-6.0.0-BETA-215.

**Comment by Flibio** [comment]
Do you have two EconomyLite JAR files installed?

**Comment by AdnanMia** [comment]
Yikes. I didn't realise. Thanks.
