### ISSUE TITLE
Concernings regarding, /baltop , command.

### ISSUE THREAD

**Issue by ghost** [Flibio/EconomyLite#34]
Well, I was playing around with my friends on one of my SpongeForge servers until I discovered something strange. When you write, /baltop , you can see all the players money but at the orange text where it says TOP BALANCES you have forgot to make an: ":" at the end of TOP BALANCES. Just so you know. :D

**Comment by Flibio** [comment]
I intentionally designed the plugin this way, but you can add a colon if you want by modifying the `command.baltop.head` message in the `messages.conf` file.
