### ISSUE TITLE
internal error occur when /money

### ISSUE THREAD

**Issue by ghost** [Flibio/EconomyLite#35]
http://pastebin.com/dYfjfsx6
server console

http://pastebin.com/dDEAmHBa
config file ( {} thing is what i changed while i configuring. i changed mysql-enabled-true, but after error occur, i turn it back to false after test it again )

mods - worldedit forge , CustomNpcs , nashorn (java language file for custom npc scripting) , Conquest Refoged
plugins - MMCrules , Splish , Boop , Holograms , Nucleus , FastLeafDecay , PermissionManager , Prism , RedProtect , MineReset , FoxGuard , FoxCore , EconomyLite , Nations

i just put EconomyLite in my mods folder and i can not use command because when i /money it says 'an internal error has occurred!'.
i can set plot prices for Nations plugin but i can not buy or sell it
im hosting on mcpro hosting server

**Comment by Flibio** [comment]
That's a current issue I'm working on a fix for.

**Comment by ghost** [comment]
ok, thanks for your hard working 👍

**Comment by Flibio** [comment]
If you could please try this development build and let me know how it works that would be great.

http://downloads.flibio.net/EconomyLite-5.0.0-2.10.0-dev3.jar

**Comment by ghost** [comment]
i think it works now
i should test with other shop-like plugins though
for now,  /money , /econ set {name} {value} 
both works fine
thanks!

**Comment by Flibio** [comment]
Glad to hear it worked out!
