### ISSUE TITLE
/eco add @p 100 gives An internal error has occurred!

### ISSUE THREAD

**Issue by DiamondArrow** [Flibio/EconomyLite#37]
Sponge: spongeforge-1.10.2-2221-5.1.0-BETA-2185
EcoLite: EconomyLite-6.0.0-2.9.0-16

EDIT:
EconomyLite-5.0.0-2.10.2
spongeforge-1.10.2-2221-5.2.0-BETA-2219

**Comment by Flibio** [comment]
Can you please add your Sponge versions and EconomyLite versions to the issue description?

**Comment by Flibio** [comment]
I'm running SpongeForge 2188, try upgrading just in case something changed. Also, I would use the release version of EconomyLite, the development builds are for API 6, as seen in the file name.

Can you also send `fml-server-latest.log` after running the command?

**Comment by DiamondArrow** [comment]
Oh sorry. I can't believe I didn't notice I was running 6
Anyways, here are my current versions:
EconomyLite-5.0.0-2.10.2
spongeforge-1.10.2-2221-5.2.0-BETA-2219

Also, fml-server-latest.log doesn't show anything after running command

> [22:12:08] [Server thread/INFO] [nucleus/]: DiamondArrow ran the command: /eco add @p 100
> [22:12:16] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
> [22:12:23] [HikariPool-1 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-1 - Pool stats (total=17, active=2, idle=15, waiting=0)
> [22:12:27] [Server thread/INFO] [nucleus/]: DiamondArrow ran the command: /homes 
>

**Comment by Flibio** [comment]
Could you try removing all other plugins temporarily and seeing if anything is causing a conflict with EconomyLite?

**Comment by DiamondArrow** [comment]
The command works with exactly the same mods and economylite config folder on a test server... Is there anything else that may be affecting it?

**Comment by Flibio** [comment]
@DiamondArrow: Hmm... that is odd, could you duplicate the server entirely and see if it still fails? If it does, remove plugins/mods one by one and see if it still fails.

**Comment by liach** [comment]
Eh... Economylite is for API 6 while SpongeForge is for API 5. Not an issue.

**Comment by DiamondArrow** [comment]
@Flibio It does. It also works with my current mods: As I mentioned on top, I moved mods folder and economylite config to a test server and /eco add @p works. However it still doesnt on the main server (with exact same mods and economylite config). I'm kind of at a loss now of what to do.

**Comment by liach** [comment]
@DiamondArrow Use the economylite for the correct API version (5 or 6)

**Comment by DiamondArrow** [comment]
thanks for pointing that out. I changed it after fiblio pointed it out earlier. Same results

**Comment by liach** [comment]
Post log again

**Comment by Flibio** [comment]
@DiamondArrow: Did you copy the exact same mod and plugin configs to the test server?

**Comment by DiamondArrow** [comment]
Same mods, brand new config files for them (except for economylite). I double checked my log file there's nothing written after running the command

**Comment by Flibio** [comment]
@DiamondArrow: Could you try copying the configs over and seeing if that causes the error to happen?

**Comment by DiamondArrow** [comment]
Just imported exact same configs. Works just as well.. going to check my world's playerdata

**Comment by DiamondArrow** [comment]
FIXED: Removed a couple corrupted files (0kb) in playerdata and stats folders

**Comment by Flibio** [comment]
Great, I'll keep this in mind if anyone else ever has the same issue.
