### ISSUE TITLE
Suggestion: Autopay by time played.

### ISSUE THREAD

**Issue by Wissi** [Flibio/EconomyLite#39]
A command for admin/server autopay for time played.
```
Maybe: /vpay <account> <player> <amount> <time/mins>
or:  /vpay <account> <amount> <time/mins>   to place in a group for Permission manager Rules? 
```
To be able to pay anyone in that group for time played?

Thanks.

**Comment by Flibio** [comment]
I'm not quite sure what you mean, could you please elaborate more?

**Comment by Wissi** [comment]
Sure, a command that can be run so a player can be paid every 10 minutes (for example). While he is logged in.
```
Maybe: /vpay <account> <player> <amount> <time/mins>
or:  /vpay <account> <amount> <time/mins>   
```

**Comment by Flibio** [comment]
Okay, I'll take a look at adding this. I'm busy the next few weekend, but I will try to do it sometime.

**Comment by Wissi** [comment]
That would be great. 
Thanks for taking the time, we really need to implement it on the server as soon as it works. 
Great plugin, we love that you can create your own currency as well.

**Comment by Flibio** [comment]
After some consideration, I am going to implement this as a separate plugin. There are currently some plugins out there that I think do this, but they don't appear to be updated so I am going to make a new one.

**Comment by Wissi** [comment]
We have not found any "working" up to date plugin, that would be great. Hopefully is something we can see soon.
Thanks.

**Comment by Flibio** [comment]
@Wissi: Can you please link a plugin with the intended functionality? I'll try to update their plugin for them.

**Comment by Wissi** [comment]
@Flibio Sure, the only simple one I could find is: PayDay [v0.5]  https://forums.spongepowered.org/t/payday-v0-5/9109
Github:  https://github.com/hsyyid/PayDay/releases
I truly hope it's a simple and fast update for you.

Thanks we really appreciate it.

I see there is and Issue about having the plugin use a custom name. I hope it can use the name that is being set by your plugin (which is changeable).

**Comment by Flibio** [comment]
I'll look into updating it pretty soon.

> I see there is and Issue about having the plugin use a custom name. I hope it can use the name that is being set by your plugin (which is changeable).

What do you mean by this?

**Comment by Wissi** [comment]
That the original PayDay has an Issue on their github that says:

> The payday message they get says dollars, would like to be able to configure the payday message for the name of our currency which is creds.

Your "EconomyLite" plugin has a configurable name for the currency, which is awesome.
Thanks for looking into it.

**Comment by Flibio** [comment]
Ok, I'll keep that issue in mind.

**Comment by Flibio** [comment]
I think I've got everything working the way I could like! [Here](https://ore.spongepowered.org/Flibio/PayDay) it is for download on Ore. Feel free to try it out and let me know how it works!
