### ISSUE TITLE
Integration/Compatibility with Pieconomy

### ISSUE THREAD

**Issue by ghost** [Flibio/EconomyLite#47]
Suggestion:

[Pieconomy's Github](https://github.com/pie-flavor/Pieconomy)

I understand that this plugin isn't released yet but it would be fantastic if the needed additions to the plugin on your side was already in place before Pieconomy's release. It looks like it just needs a stopper in place if inventory space doesn't exist.  

> This plugin runs a few edge cases you don't expect to see in economy plugins. Player accounts can and will return ResultType.ACCOUNT_NO_SPACE. They can even return that when withdrawing, due to the making of change. They can even return that, but be successful on a larger amount, due to a full inventory but non-full stacks. Server accounts can report a balance, and successfully withdraw a balance, but return ACCOUNT_NO_SPACE if you try to put it back again due to the currency not being allowed on that account. They can also have negative values on any given currency.

> However, I still have no idea how Contexts work, or what they even mean, so I ignore them completely.

**Comment by Flibio** [comment]
Can you please elaborate on the what the issue is / what I need to implement? I don't quite understand the issue.

**Comment by ghost** [comment]
From what Pie says, It's up to whatever plugin does the economy request how to handle a lack of space for money. (copied and pasted from his github for Pieconomy. It looks like a stopper will need to be put in place on the main eco plugin's side if a player does not have the required space for the items his plugin generates. 

It looks like his plugin will be sending out a message: "resultType.ACCOUNT_NO_SPACE" if the inventory is full and I assume your (and others) plugin will need to look for that messsage and send an error to the player saying they cannot pay them due to a full inventory or such.

**Comment by Flibio** [comment]
So you are saying that Pieconomy requires a main economy plugin to function? To me this disclaimer is for plugins such as a shop plugin that require an economy plugin to function. Sorry if I'm understanding this incorrectly.

**Comment by ghost** [comment]
I am stupid. 

For some crazy reason I was thinking this was a bolt on that would let another plugin manage the currency and it just convert it to items. 

Please forgive me for wasting your time with this. I'll close this suggestion..

**Comment by Flibio** [comment]
No worries! I understand why you thought that.
