### ISSUE TITLE
Convert bukkit plugin into sponge? [ PlayerPoint]

### ISSUE THREAD

**Issue by kizza5161** [Flibio/EconomyLite#50]
I used playerpoint from bukkit, I do not know how the sponge's analogue plug-in, can you help me convert it to work on sponge or create a plugin for sponge? - I can pay the fee according to your request. ;)

 Thanks

[PlayerPoints.zip](https://github.com/Flibio/EconomyLite/files/1263262/PlayerPoints.zip)

**Comment by kizza5161** [comment]
I am using the latest version SpongeForge 1.10.2 has been released

**Comment by Flibio** [comment]
Unfortunately, I'm not currently doing any private work. Next time please contact me on Gitter if you wish to communicate, as GitHub issues is not a proper communication form.

Thanks!
