### ISSUE TITLE
NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause 

### ISSUE THREAD

**Issue by ziceptor** [Flibio/EconomyLite#52]
forge-1.12.2-14.23.0.2486-universal.jar
spongeforge-1.12.2-2486-7.0.0-BETA-2645.jar
EconomyLite-5.0.0-2.12.0.jar

https://gist.github.com/ziceptor/358029d74f67b441ea30c9f06a1bf616

**Comment by Flibio** [comment]
EconomyLite needs to be updated for the latest Sponge API, I'll try to do that sometime soon.

**Comment by Dockter** [comment]
I have a PR that is waiting to be accepted to resolve this issue.

**Comment by ziceptor** [comment]
@mcsnetworks Thank you.

**Comment by Flibio** [comment]
#53
