### ISSUE TITLE
Multi-currency and payment

### ISSUE THREAD

**Issue by Krosta8** [Flibio/EconomyLite#55]
Hello,
I have a problem with multi-currency support.
I want to use it for two currencies with VirtualChest and I can’t get it to work properly. Everytime its using the first currency.
And with PlaceHolderAPI I can’t get the value of the currencies properly. I tried to use %economy_balance_token% and %economy_balance_kredit% then %economy_balance_[token]% and %economy_balance_[kredit]%. Again, its just get back the balance of the first currency.

Does anyone know the solution for this?

PS: Sponge 1.10.2 API 5.2.0, EconomyLite 2.12.0

**Comment by Flibio** [comment]
Have you tried asking the VirtualChest developer? I'm not sure how PlaceHolderAPI or VirtualChest works, so I would was those developers.

**Comment by Krosta8** [comment]
Not yet, but I think, that there should be still problem with the set, add and remove money from the currencies. I can run a command on click in the GUI, but there is no option like "econ remove Krosta8 10 kredit", so I'm not able to set from which currency it should remove/add money.

Is this possible in future update or is it possible now somehow?

I will try to contact the developers of both plugins, but I need to know, if I can use your plugin at all for my needs.

**Comment by Flibio** [comment]
Currently EconomyLite uses 1 currency for all commands, which be switched via the `/currency` command. I haven't found the time to add the ability to specify which currency on a per-command basis (#44), but I hope to do it soon. 

EconomyLite is not responsible for how PlaceHolderAPI retrieves currency values, so you would have to ask those developers. Sorry I can't you help you in that area.

Thanks for your interest in EconomyLite!

**Comment by Krosta8** [comment]
Ok, thank you anyway. I just figured out, that the placeholder API shows the currently selected currency. So I just have to use two commands instead of one. Firstly switch automatically to kredit/token and then proceed the add/remove.

I will stay tunned for new updates!
Thank you a lot. 🙂

**Comment by Flibio** [comment]
Good luck with your server!
