### ISSUE TITLE
servr crashing 

### ISSUE THREAD

**Issue by afghan007** [Flibio/EconomyLite#57]
06.11 00:53:33 [Multicraft] Not restarting crashed server.
06.11 00:53:33 [Disconnect] User afghan007 has disconnected, reason: Server shutting down
06.11 00:53:33 [Multicraft] Server stopped
06.11 00:53:33 [Multicraft] Server shut down
06.11 00:53:32 [Server] Server Shutdown Thread/INFO Saving players
06.11 00:53:32 [Server] Server Shutdown Thread/INFO Stopping server
06.11 00:53:32 [Server] Server thread/INFO [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
06.11 00:53:32 [Server] Server thread/INFO [nucleus]: Nucleus is performing server shutdown tasks.
06.11 00:53:32 [Server] Server thread/INFO [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Closed.
06.11 00:53:32 [Server] Server thread/INFO [com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Close initiated...
06.11 00:53:32 [Server] Server thread/INFO [FML]: Holder lookups applied
06.11 00:53:32 [Server] Server thread/INFO [FML]: Applying holder lookups
06.11 00:53:32 [Server] Server thread/INFO Saving worlds
06.11 00:53:32 [Server] Server thread/INFO Saving players
06.11 00:53:32 [Server] Server thread/INFO Stopping server
06.11 00:53:32 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2017-11-06_00.53.32-server.txt
06.11 00:53:32 [Server] INFO ... 23 more
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
06.11 00:53:32 [Server] INFO Caused by: java.lang.NullPointerException
06.11 00:53:32 [Server] INFO ... 23 more
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
06.11 00:53:32 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.EventContext
06.11 00:53:32 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) ~[MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[md.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1621) ~[mp.class:?]
06.11 00:53:32 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:483) ~[SpongeForgeEventFactory.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeForgeEventFactory.callPlayerLoggedInEvent(SpongeForgeEventFactory.java:1190) ~[SpongeForgeEventFactory.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) ~[EventBus.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_EconomyEventHandler_onPlayerSpawn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
06.11 00:53:32 [Server] INFO at uk.co.haxyshideout.pixelmoneconomybridge.events.EconomyEventHandler.onPlayerSpawn(EconomyEventHandler.java:79) ~[EconomyEventHandler.class:?]
06.11 00:53:32 [Server] INFO at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:58) ~[LiteEconomyService.class:?]
06.11 00:53:32 [Server] INFO at io.github.flibio.economylite.CauseFactory.create(CauseFactory.java:34) ~[CauseFactory.class:?]
06.11 00:53:32 [Server] INFO java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/EventContext
06.11 00:53:32 [Server] Server thread/ERROR Encountered an unexpected exception
06.11 00:53:32 [Server] Server thread/ERROR [FML]: 3: ASM: uk.co.haxyshideout.pixelmoneconomybridge.events.EconomyEventHandler@30b27514 onPlayerSpawn(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
06.11 00:53:32 [Server] Server thread/ERROR [FML]: 2: ASM: com.pixelmonmod.pixelmon.listener.PixelmonPlayerTracker@7278d63f onPlayerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
06.11 00:53:32 [Server] Server thread/ERROR [FML]: 1: ASM: Forge playerLogin(Lnet/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
06.11 00:53:32 [Server] Server thread/ERROR [FML]: 0: NORMAL
06.11 00:53:32 [Server] Server thread/ERROR [FML]: Index: 3 Listeners:
06.11 00:53:32 [Server] INFO ... 23 more
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
06.11 00:53:32 [Server] INFO Caused by: java.lang.NullPointerException
06.11 00:53:32 [Server] INFO ... 23 more
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
06.11 00:53:32 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.EventContext
06.11 00:53:32 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
06.11 00:53:32 [Server] INFO at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1621) [mp.class:?]
06.11 00:53:32 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:483) [SpongeForgeEventFactory.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at org.spongepowered.mod.event.SpongeForgeEventFactory.callPlayerLoggedInEvent(SpongeForgeEventFactory.java:1190) [SpongeForgeEventFactory.class:1.10.2-2477-5.2.0-BETA-2698]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) [EventBus.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
06.11 00:53:32 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_EconomyEventHandler_onPlayerSpawn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
06.11 00:53:32 [Server] INFO at uk.co.haxyshideout.pixelmoneconomybridge.events.EconomyEventHandler.onPlayerSpawn(EconomyEventHandler.java:79) ~[EconomyEventHandler.class:?]
06.11 00:53:32 [Server] INFO at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:58) ~[LiteEconomyService.class:?]
06.11 00:53:32 [Server] INFO at io.github.flibio.economylite.CauseFactory.create(CauseFactory.java:34) ~[CauseFactory.class:?]
06.11 00:53:32 [Server] INFO java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/EventContext
06.11 00:53:32 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@7ef9ad87:

**Comment by Flibio** [comment]
What SpongeAPI version and EconomyLite version are you using?
