### ISSUE TITLE
"@a" or "*" needed for {player}

### ISSUE THREAD

**Issue by Philosyang** [Flibio/EconomyLite#59]
I would like to give the players $1 for every minute they're online.
I used other plugins to repeat the command "**/eco add @a 1**".
Things go well when there's only 1 people online.
Things don't work when there are 2 and 2+ people online...
I've tried to repeat the command in-game, in a command block, and at the console.

All of them returned the error below:
![image](https://user-images.githubusercontent.com/24841393/32549526-cb5f4734-c4c4-11e7-9ccd-8afff327afed.png)
![image](https://user-images.githubusercontent.com/24841393/32549539-d56a8cb6-c4c4-11e7-957a-7f666e44940b.png)

Does anyone know any other way to achieve this? Is there an alternative sponge command that will work?
Thanks!

**Comment by tianji1993** [comment]
got same problem here.

**Comment by Flibio** [comment]
Is there any error in the console?

**Comment by Flibio** [comment]
If you want to play players at a set interval, check out [PayDay](https://ore.spongepowered.org/Flibio/PayDay).

**Comment by Philosyang** [comment]
No errors or warning messages at the console.
Only a red line of “An internal error has occurred!” in game, at command block output, and at the console.

**Comment by Philosyang** [comment]
Thanks for that Payday plugin, will try it ASAP.
