### ISSUE TITLE
Possible EconomyService bug? idk.

### ISSUE THREAD

**Issue by KhaozFrost** [Flibio/EconomyLite#60]
https://github.com/rojo8399/PlaceholderAPI/issues/42
https://github.com/ustc-zzzz/VirtualChest/issues/35

" on API 7 I am having a hard time replicating the issues: with no economy plugin installed, the economy placeholders throw out the error stating that there is no economy plugin; with Total Economy installed (just as a test case), economy placeholders worked. On a fresh install I parsed balance (got 100), bal_format (got $100.00), and several other placeholders and could not get the placeholders to not parse.

I think the issue could boil down to two things:

    There is no installed economy plugin. This one is pretty self-explanatory, an economy plugin needs to be installed for economy placeholders to work. If a player has no money, how can I get how much money they have? ;)
    The installed economy plugin does not support EconomyService. This is an issue you would have to bring up with the author of your economy plugin, as they are not properly making their plugin.

In either case, I could not replicate issues with the placeholder when I had a proper economy plugin installed, so I am not sure what I can do."

**Comment by Flibio** [comment]
I'm not sure what the issue is exactly.

> In either case, I could not replicate issues with the placeholder when I had a proper economy plugin installed.

It doesn't sound like there is any issue with EconomyLite.
