### ISSUE TITLE
Lag when retrieving account/balance

### ISSUE THREAD

**Issue by Eufranio** [Flibio/EconomyLite#61]
Hello. I have a (private) plugin that has a command that checks the balance of the player on it's logic. For some reason, maybe database related, when my user runs that command, it takes up to 30 seconds to process everything, and lags the server when doing it. That's the relevant method I have, using the plain SpongeAPI:
```
public boolean canGet(Player player) {
        EconomyService service = Sponge.getServiceManager().provide(EconomyService.class).get();
        UniqueAccount acc = service.getOrCreateAccount(player.getUniqueId()).orElse(null);
        if (acc != null) {
            if (acc.getBalance(service.getDefaultCurrency()).compareTo(this.cost) < 0) {
                return false;
            }
        }
        return false;
}
```
As you can see, I'm just checking the balance of the account of the player. On a plain server with a fresh EconomyLite database, this doesn't happen. 
![img](https://image.prntscr.com/image/NsccS5azRBmI2rVkZkDWHw.png)

**Comment by Flibio** [comment]
Are you using MySQL or H2?

**Comment by Eufranio** [comment]
H2 (hence the screenshot).

**Comment by Flibio** [comment]
How many users are in the database?

**Comment by Eufranio** [comment]
I'm not sure, but there are a lot...

**Comment by Flibio** [comment]
Okay, could you please send the full relevant server logs for when this method is run?

**Comment by Eufranio** [comment]
There's nothing really relevant in the logs: https://gist.github.com/anonymous/47b6e7a7c289e9784ca728da4623cf62
The method is called when the player runs /ranks.

**Comment by Flibio** [comment]
Do you have the debug EconomyLite logging on?

**Comment by Eufranio** [comment]
No. Log with it enabled: https://gist.github.com/anonymous/764825d1fc7e1212c3e7feb0afae5042

**Comment by Flibio** [comment]
It would appear the balance checker is running in a loop. Do you have any code that does this?

**Comment by Eufranio** [comment]
Yes. In this specific case, it looped 16 times, but the time still a lot: 30 seconds is A LOT. With only 1 call, it takes about 2 seconds to get the balance.

**Comment by Flibio** [comment]
If 1 call takes 2 seconds then 16 taking 30 seconds makes sense. Is there any specific reason the balance call needs to be repeated 16 times in rapid succession?

**Comment by Eufranio** [comment]
Yes, there is.

**Comment by Flibio** [comment]
Could you please let me know? Maybe there is some sort of optimization I could do.

**Comment by Eufranio** [comment]
My plugin has a GUI where there are ranks that you can buy. I need the balance of the player to display in the items representing the ranks without withdrawing from the player yet (and that's why I'm not using the TransactionResult here). There are 16 ranks, so thats why it called the method 16 times.

I can yes optimize my code, I am going to do it, but even after optimizing it, the only one call to get the balance of the player will still take 2 seconds, and that is a big amount of time for a simple operation like that.

My suggestion is that, if you can, optimize the database. Cache the accounts when possible instead querying to the storage on every request, update/retrieve from cache when neccessary, etc. Not only me but ALL plugins that use the Sponge's Economy API are suffering with your implementation when running with a big storage...

**Comment by Flibio** [comment]
Caching is what I thought of as well, I'll take a look at adding it sometime soon. I'm busy with other things right now, but in a few weeks I should be able to get it added.
