### ISSUE TITLE
Compiled versions

### ISSUE THREAD

**Issue by rodrigofrcs** [Flibio/EconomyLite#62]
Hello, are not the compiled versions available? The site link does not work.

**Comment by Flibio** [comment]
Which link does not appear to be working?

**Comment by rodrigofrcs** [comment]
In http://flibiostudio.github.io/EconomyLiteDocs/index.html, "Here" on Downloads topic. In github I only found "source code", is there a jar of the plugin?

**Comment by Flibio** [comment]
I have stopped doing development builds, but the plugin is downloadable on Ore.
