### ISSUE TITLE
Can't use custom currency

### ISSUE THREAD

**Issue by BrainStone** [Flibio/EconomyLite#64]
Whenever I configure a custom currency, the default coins get added back and used as a default.

**Comment by Flibio** [comment]
How exactly are you configuring the currency?

**Comment by BrainStone** [comment]
What I configure:

```
cmark {
    plural=C-Mark
    singular=C-Mark
    symbol=CM
}
current=cmark
```

How the plugin changes it:

```
cmark {
    plural=C-Mark
    singular=C-Mark
    symbol=CM
}
coin {
    plural=Coins
    singular=Coin
    symbol=C
}
current=coin
```

Configuring it like below works, though that's not ideal!

```
coin {
    plural=C-Mark
    singular=C-Mark
    symbol=CM
}
current=coin
```

**Comment by Flibio** [comment]
I would use the in-game currency management via the `currency` command. [Documentation](http://flibiostudio.github.io/EconomyLiteDocs/commands.html).
