### ISSUE TITLE
Issue with latest spongeforge 

### ISSUE THREAD

**Issue by JoeSGT** [Flibio/EconomyLite#67]
Hello
your plugin EconomyLite broke https://gist.github.com/JoeSGT/8aab0b2f99295947c42d4a9656c84a48
with Spongeforge  version 1.12.2-2611-7.1.0-BETA-2940
EconomyLite version i use is 7.0.0-2.13.0

**Comment by Flibio** [comment]
Could you try the latest SpongeForge? Build 2942.

**Comment by JoeSGT** [comment]
ah that fix it thanks you so much i didn't realize that they just dated again thanks
