### ISSUE TITLE
adding and removing balance to second currency

### ISSUE THREAD

**Issue by PharaohMo** [Flibio/EconomyLite#68]
Hello, I wanted to know if it was possible to add or remove from someones secondary balance. My main balance is pokedollars and second is tokens. I want to give tokens as a voting reward and leveling up reward. And then I want to take away tokens using virtualchest interfaces. But I still want pokedollars to be the main currency used for everything else.

**Comment by Flibio** [comment]
I believe it is up to your plugins such as VirtualChest and voting reward plugin to implement this, EconomyLite already supports modifying all currencies via the API.

**Comment by PharaohMo** [comment]
but can u do it with commands? or do I have to use a second plugin to do this?

**Comment by Flibio** [comment]
It is currently not possible with commands; however, it is being added in EconomyLite 3.0.0 (#44).
