### ISSUE TITLE
Lags problem

### ISSUE THREAD

**Issue by PixelmonPRO** [Flibio/EconomyLite#70]
Good afternoon! I've been using this plugin for a long time, and since version 1.12.2 (Sponge 2990) I've encountered very big problems, now I'll try to describe. I use MySQL, and have next problems:
1. command /baltop not work, have next errors: https://gist.github.com/PixelmonPRO/dfd1854fbde61ef817486154908dc6cc
2. My server use economy very much, i use many transactions, players like `Virtual Chest menu (Placeholder API check economy balance), Pixelmon Money (money from Pokemons), and many similar possibilities. I have one server in Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 cores), and players online higher 60-65 players -> TPS falls sharply slowdown, wherever there are queries to the economy - have high timings.
3. I bought a new server machine and decided to connect to the old database on another machine (machines have 1gb/s ethernet), when trying to query the economy, the following is observed, example test request balance VirtualChest menu: https://timings.aikar.co/?id=8b53021a5637410aaf808950a87b6ae5

**Comment by PixelmonPRO** [comment]
Version EconomyLite v2.13.0, API 7 Sponge 2990, Java 8 JKD 161 and test 151, 162 builds, Debian 8 and another machine Debian 9.

**Comment by Flibio** [comment]
There is a fix planned. However, I am incredibly busy at the moment. I'll try to resolve as soon as I can.

**Comment by Flibio** [comment]
This should be resolved, let me know how it works for you!
