### ISSUE TITLE
No money received message

### ISSUE THREAD

**Issue by SnowBlitzz** [Flibio/EconomyLite#71]
On the newer versions of sponge (3002), the player who receives money via /pay doesn't get any message that they got paid.

**Comment by Flibio** [comment]
I'll look at this when I have time.

**Comment by Heriptik** [comment]
Yes, this problem is painful

**Comment by Shmeeb** [comment]
A fix soon would be mucho appreciated

**Comment by Flibio** [comment]
I should have time this weekend
