### ISSUE TITLE
Error and MySQL sync money?

### ISSUE THREAD

**Issue by PixelmonPRO** [Flibio/EconomyLite#72]
Thanks for update 2.14.0! I have error in launch server: https://gist.github.com/PixelmonPRO/601699f322e165e8d63e203fa648e5bc
And a very big problem. MySQL update money, but not sync in game. I have a trading module on the my site, and after the trade a new balance in the game will not be established, and if I make any economic actions in the game - the balance will be updated with a new one (and the money received from the site will be lost). Example: i have 2000 money -> sell minecraft blocks in my site -> new balance 3000, MySQL table money update to 3000 -> in game i have 2000 (no update), any eco operation in game, bal in game now 2100, and MySQL update table money to 2100.

**Comment by Flibio** [comment]
This should be fixed in version 2.14.1. Let me know if it works for you!
