### ISSUE TITLE
Spigot/Paper Compilation

### ISSUE THREAD

**Issue by Resoluciones** [Flibio/EconomyLite#74]
Hi! Great plugin, congratulations!

Would it be possible someone compile it against last spigot or paper in a .jar?

Thank you very much!!!!

**Comment by Flibio** [comment]
Unfortunately, I cannot do so. Sponge is a completely different platform than Spigot and Paper. I would have to completely rewrite the plugin to support those two platforms. EconomyLite will remain only a Sponge plugin for the foreseeable future.
