### ISSUE TITLE
How can I contact you

### ISSUE THREAD

**Issue by int3rno** [Flibio/EconomyLite#75]
I need to contact you, please leave a link as I can contact you, Facebook or something. I want to buy a small plugin for Sponge. Thank you!

**Comment by Flibio** [comment]
You either send me a private message on the [Sponge Forums](https://forums.spongepowered.org) or [Gitter](http://gitter.im). There we can discuss further communication options.

**Comment by int3rno** [comment]
Thank you, i send message in Gitter.
