### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by ghost** [Flibio/EconomyLite#76]
Since I upgraded from 2.13.0 to 2.14.2, the player's balance data could not be used together, and they would all start from 0 coin, because there was a problem with the 2.13.0 /pay command that forced me to upgrade.

**Comment by Flibio** [comment]
Can you please describe the issue in more detail?

**Comment by ghost** [comment]
I use the 2.13.0 version to read the data.mv.db file normally, but upgrading to the 2.14.2 version fails to read it correctly. All players' balance data is zeroed.
Here is the link to my data file https://www.dropbox.com/s/blxmlfwwhi3jk1n/economylite%20data.zip?dl=0

**Comment by Flibio** [comment]
This is the pre-2.14.2 data?

Also please send your configuration files.

**Comment by ghost** [comment]
This is the 2.13.0 configuration file https://www.dropbox.com/s/uul28o6bmjmkcbe/config.conf?dl=0

**Comment by Flibio** [comment]
Could you send the 2.13.0 currency configuration as well?

**Comment by ghost** [comment]
This is my currencies.conf link https://www.dropbox.com/s/h4ccoj5uds6tmxu/currencies.conf?dl=0 Is it because of the problem I modified?

**Comment by Flibio** [comment]
There aren't any errors in the console, correct?

**Comment by Flibio** [comment]
Did you solve your issue?
