### ISSUE TITLE
vbalance

### ISSUE THREAD

**Issue by voignar** [Flibio/EconomyLite#78]
for use vbalance its necessary create new currency? I've set the vbalance permissions but nobody can use it

I mean, with vbalance can I have a second currency inside the server?

**Comment by Flibio** [comment]
Virtual accounts do not require an additional currency to be created. However, if you want to create a new currency it is possible using the `/currency` commands.

**Comment by voignar** [comment]
But its possible add and remove currency without make a switch currency?

**Comment by Flibio** [comment]
Not yet, but the feature has been requested in #44.
