### ISSUE TITLE
Request: Re-do some commands and more

### ISSUE THREAD

**Issue by GershonR** [Flibio/EconomyLite#8]
- Ability to use tab to complete a players name
- Change the /pay [amount] [player] to /pay [player] [amount]
- Remove /playerbalance and have /balance (player optional arguement) and use /business balance
- SQLlite storage rather than flatfile
- Possibly add /money as an alias of /balance
- Add a /econ to see the current version of the plugin

**Comment by Flibio** [comment]
I will integrate these features into EconomyLite 2.0.0.

**Comment by MichaelFedora** [comment]
@GershonR , according to the [Sponge docs](https://docs.spongepowered.org/en/plugin/database.html), SQlite is "strongly discouraged". I would instead use H2.

Some notes for implementation;

`[player]` tab-completion can be done, by using the [`GenericArguments.player(...)`](https://jd.spongepowered.org/4.0.3/org/spongepowered/api/command/args/GenericArguments.html#player-org.spongepowered.api.text.Text-) or the [`GenericArguments.playerOrSource(...)`](https://jd.spongepowered.org/4.0.3/org/spongepowered/api/command/args/GenericArguments.html#playerOrSource-org.spongepowered.api.text.Text-) method (and the latter would probably be better, for code simplification I guess).
