### ISSUE TITLE
Can't use unique characters

### ISSUE THREAD

**Issue by Shybella** [Flibio/EconomyLite#80]
I'm trying to set the ` symbol=$` using a $ sign and the plugin seems to bomb out when doing so. 

`coin {
    plural=Shekels
    singular=Shekel
    symbol=$
}
current=coin`

Is this a known problem or unable to use symbols such as $

Thank you.

**Comment by Flibio** [comment]
Try using quotation marks around the dollar sign. `symbol="$"`

**Comment by Shybella** [comment]
Yes, thank you.
