### ISSUE TITLE
Loan incorrect amount

### ISSUE THREAD

**Issue by Shybella** [Flibio/EconomyLite#81]
I'm taking a loan of 1000 but offers 500 but charges my loan balance for 2,500.

Interest rate is at 5% I tried setting it to zero but loan command stops working when I do that.

Max loan amount is set to 2500.

http://prntscr.com/jnvowt

**Comment by Flibio** [comment]
What does your EconomyLite configuration look like?

**Comment by Shybella** [comment]
`confirm-offline-payments=true
# Enables or disables debug logging.
debug-logging=true
default-balance {
    # Default balance of player accounts.
    player=0
    # Default balance of virtual accounts.
    virtual=0
}
modules {
    loan {
        debtor-perms {
            "reward.permission"=true
        }
        enabled=true
        interest-rate=5
        max-loan-balance=2500
    }
    mysql {
        database=database
        enabled=false
        hostname=hostname
        password=password
        port="3306"
        username=username
    }
}
# If enabled players will be notified when an admin changes their balance
notify-on-admin-commands=false
`

**Comment by Shybella** [comment]
https://pastebin.com/raw/vWcttHmt

**Comment by Flibio** [comment]
You want to set the interest rate to `1.05` not `5`. That should solve your issues. The maximum loan balance is calculated with interest in mind, so that is why EconomyLite won't offer a loan of $1000.

**Comment by Shybella** [comment]
Yes, thank you again!
