### ISSUE TITLE
Tax system

### ISSUE THREAD

**Issue by Shybella** [Flibio/EconomyLite#82]
Simple tax system designed around class bracket levels. 

Tax income over set time interval with control of percentage of income taxable. 
Ex: income is 10,000 over 24 hours. Income tax is 10% due every 24 hours. Your account gets charged tax income amount of 1,000. 

Any bracket level can be added to the config. If you want to charge 5% at 5,000 or 2% at 10,000.
Have the taxed income is sent to a virtual account. 

If you want to get crazy. I'm already asking a lot. 

Federal tax refunds. Refund a set percentage of their taxed income back in a set time interval. 

Thanks.

**Comment by Flibio** [comment]
This is quite a large feature, I will consider adding it one day.

**Comment by Shybella** [comment]
This would be such a great feature. Just a simple income tax system.

**Comment by Shybella** [comment]
https://github.com/randombyte-developer/taxation
