### ISSUE TITLE
Baltop leader board gives [sponge] 100,000,000.00

### ISSUE THREAD

**Issue by ghost** [Flibio/EconomyLite#84]

**Comment by Flibio** [comment]
Can you describe your issue in more detail please?

**Comment by ghost** [comment]
@Flibio The leaderboard has a number 1 leader with 100,000,000.00 and we are not sure why. We cannot remove it and we cannot find any saved file from sponge.

**Comment by Flibio** [comment]
Who is listed at owning this account?

**Comment by ghost** [comment]
It simply says [Sponge] and nothing else. It is not assigned to any player, no one can access it, nor is it found anywhere in any saved files.

**Comment by Flibio** [comment]
Does `/vbalance Sponge` return anything?
Or `/balance Sponge`?

**Comment by ghost** [comment]
Tried both. /balance reports and old player because his name was similar to "Sponge" but lists only $4,000. /vbalance gives 0.00 coins for "Sponge"

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34326166/41947487-d4241c52-7985-11e8-9bf8-332b7118098a.png)

Here is the actual picture for the bug. Is the same in game

**Comment by Flibio** [comment]
Could you send your database files so I could try to reproduce this issue?
