### ISSUE TITLE
[Suggestion] Default debug logging is OFF

### ISSUE THREAD

**Issue by Rasgnarok** [Flibio/EconomyLite#85]
Pretty simple, could the default config have debug logging turned off? Most server owners have no idea it is an option, and honestly, EconomyLite has never given me a reason to have this on in the last 2 years of me using it. Logging can get pretty spammy, so by default it holds no use and can be detrimental to reading `debug.log`s.

thanks!

(example) 
![image](https://user-images.githubusercontent.com/18584380/41614780-5cab814c-73c7-11e8-9783-8f7367603645.png)

**Comment by Flibio** [comment]
I'll consider adding it to the next update.

**Comment by Rasgnarok** [comment]
Any update on this? It really makes reading logs terrible: 
![image](https://user-images.githubusercontent.com/18584380/44604107-d8e98500-a7b2-11e8-8ba4-b20c327c4ab2.png)

**Comment by Flibio** [comment]
I'm sorry, I'm terribly busy at the moment. I'll do it when I can.

**Comment by Flibio** [comment]
4b342f4
