### ISSUE TITLE
SQL Manager is leaking handles

### ISSUE THREAD

**Issue by Dockter** [Flibio/EconomyLite#90]
We added a leak detector to SpongeForge and your mod tripped our alerts:

https://gist.github.com/Dockter/fac8e866a0271dcfef574b93ef5114cd

This is how we fixed Almura when it encountered the same issue:

https://github.com/AlmuraDev/Almura/commit/2268fe001e37bc98c8cfa3a8e8a0254774fc561c

**Comment by XakepSDK** [comment]
As i see, `SqlManager` is really bad, you don't need to cache `Connection`, `SqlService` will do this for you. You just need to get `DataSource` and save it somewhere. Then you can get connections from it. Don't forget to close these connections.

**Comment by Rasgnarok** [comment]
https://gist.github.com/Rasgnarok/0c73e6204dd28eb8b3cd62d18f5493fe

with Spongeforge 3358

**Comment by Flibio** [comment]
I'll fix this as soon as I can.

**Comment by Flibio** [comment]
@Dockter I've got the fix working for MySQL but not for the H2 database. Do you know of the differences or what could be going wrong?

I updated the [SQL Manager](https://github.com/FlibioStudio/Utils/blob/master/src/main/java/io/github/flibio/utils/sql/SqlManager.java) but it doesn't function at all when using the local H2 database. [Here is a dev build](https://www.dropbox.com/s/fxtdl6rb7gyilg4/EconomyLite-7.1.0-2.14.4.jar?dl=1). Would you be willing to try it and tell me if it works at all with the local H2 database?

**Comment by XakepSDK** [comment]
You should close everything, Connections, PreparedStatements, ResultSets. By default, if something implements Cloaseable/AutoCloseable interface - close early as possible to avoid any possible leak.
Look at example:
https://github.com/SpongeAPI-Russian/SqlServiceExample/blob/master/src/main/java/com/spongeapi/tutorial/SqlServiceExample/StorageManager.java

**Comment by Dockter** [comment]
@Flibio what is the issue you are working with on h2?
