### ISSUE TITLE
Weird output when getting default currency

### ISSUE THREAD

**Issue by Jess4Tech** [Flibio/EconomyLite#91]
Calling economyService.getDefaultCurrency() returns io.github.flibio.economylite.impl.LiteCurrency@4ca26acb
http://prntscr.com/kf2kmq
EDIT: Provide picture

**Comment by 0Fox** [comment]
What's weird about it?

**Comment by Flibio** [comment]
That is what it should return, a currency object. If you want the currency name or you have to call one of the methods in the `Currency` class such as `getDisplayName()`.

**Comment by Jess4Tech** [comment]
Thank you!!
