### ISSUE TITLE
Bug using MultiCurrencyStuffs 

### ISSUE THREAD

**Issue by gearkill** [Flibio/EconomyLite#98]
every time I try to use the MultiCurrencyStuffs (/ meco <set> add / remove> <player> <currency> <amount>) it generates an error and the amount is not added to the database
https://pastebin.com/shaacqdK

version

MultiCurrencyStuffs-1.2
EconomyLite-7.1.0-2.14.4
more works perfectly in EconomyLite-7.0.0-2.13.0

**Comment by Flibio** [comment]
Is MultiCurrencyStuffs a private plugin? I cannot seem to find it.

**Comment by gearkill** [comment]
yay , Justin Plugin
https://cdn.discordapp.com/attachments/396833841211506688/485586725993709578/MultiCurrencyStuffs-1.2.jar

**Comment by gearkill** [comment]
Yes, justin plugin
http://www.mediafire.com/file/820zzby9a3ostzd/MultiCurrencyStuffs-1.2.jar/file

**Comment by Flibio** [comment]
Okay, I'll check it out.
